front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /

back_officeback:
    resource: "@BackOfficebackBundle/Resources/config/routing.yml"
    prefix:   /back
inter_cin:
    resource: "@InterCinBundle/Resources/config/routing.yml"
    prefix:   /

compte_cp:
    resource: "@CompteCPBundle/Resources/config/routing.yml"
    prefix:   /
egov_main:
    resource: "@EgovMainBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: @AppBundle/Controller/
    type:     annotation
fos_user:
 resource: "@FOSUserBundle/Resources/config/routing/all.xml"
