front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /

back_officeback:
    resource: "@BackOfficebackBundle/Resources/config/routing.yml"
    prefix:   /back

app:
    resource: @AppBundle/Controller/
    type:     annotation
fos_user:
 resource: "@FOSUserBundle/Resources/config/routing/all.xml"
