security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CLIENT:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_AGENT_MUNICIPALITE: ROLE_MUNICIPALITE
        ROLE_AGENT_INTERIEUR: ROLE_INTERIEUR
        ROLE_AGENT_POSTE: ROLE_POSTE
        ROLE_AGENT_MINISTRE: ROLE_MINISTRE
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
                login_path:             fos_user_security_login 
                check_path:             fos_user_security_check

            logout:       
                path: logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/affichage, role: ROLE_CLIENT }