my_app_user_homepage:
    path:     /hello
    defaults: { _controller: MyAppUserBundle:Default:index }
fos_user:
 resource: "@FOSUserBundle/Resources/config/routing/all.xml"
my_app_user_home:
    path:     /login2/reg
    defaults: { _controller: MyAppUserBundle:Default:loginInsc }